apiVersion: v1
kind: Service
metadata:
  name: client-lb
  namespace: dev
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    run: next-client
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: server-lb
  namespace: dev
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    run: fastapi-server
  type: LoadBalancer
