apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-client
  namespace: dev
spec:
  selector:
    matchLabels:
      run: next-client
  replicas: 3
  template:
    metadata:
      labels:
        run: next-client
    spec:
      containers:
      - name: next-client
        image: onboarding-socar-web
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: config-prod
        

