apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  namespace: dev
spec: 
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /vm-mount-path #로컬 머신 볼륨을 마운트시킨 Minikube VM의 PATH

